### PR TITLE
prepare move to telescope project

### PR DESCRIPTION
**Pull request by weeman1337**
@Conni2461 as preparation moving this one to the telescope project

### CODE REVIEW

**Comment by weeman1337** [comment]
Another PR for the REUSE follows after moving it

**Comment by Conni2461** [comment]
works for me. I dont have a big issue saying that the development isnt happening here.

But issues need to be enabled here none the less and you need to fill in the license with a `<year>` and `<copyright holders>`. 

Also maybe not write everything in one line :laughing:

**Comment by Conni2461** [comment]
I dont have access to settings. Idk

image

**Comment by weeman1337** [comment]
Thanks for the response @Conni2461 

> works for me. I dont have a big issue saying that the development isnt happening here.

I have removed that note in the PR.

> you need to fill in the license with a <year> and <copyright holders>.

Licences are properly noted. Maybe you can clarify on that point please?

> Also maybe not write everything in one line laughing

What has been written into a single line? Could you please linke the code?

> I dont have access to settings.

Unfortunately GitHub doesn't seem to support granting that for my personal repo :/ So maybe just create another repo in the telescope organisation and then push this code :shrug:

**Comment by Conni2461** [comment]
You should have an invite.

I meant that these placement holders are not filled in https://github.com/weeman1337/telescope-live-grep-raw.nvim/blob/53d48409aa60de1b2accaa2dad0de7c68d645a25/LICENSES/MIT.txt#L3

**Pull request merged**
